---
title: "Protótipo DRG - Ortopedia"
output: 
  flexdashboard::flex_dashboard:
     social: menu
     source_code: embed    
     vertical_layout: fill
     runtime: shiny
---

```{r setup, include=FALSE}
library(flexdashboard)
library(shiny)
library(DT)
library(writexl)
library(readxl)
library(rhandsontable)
options(shiny.maxRequestSize = 10 * 1024^2)
```

Teste 1
=====================================  


Inputs {.sidebar data-width=250}
-----------------------------------------------------------------------

```{r}

fileInput("file1", "Select xlsx File to Import", accept = ".xlsx")

actionButton("run_button", "Run Analysis", icon = icon("play"), style = "width:150px")

br()
br()

actionButton("delete_button", "Clear Analysis", icon = icon("trash"), style = "width:150px")
```

Column {.tabset}
-----------------------------------------------------------------------


### Entrada

```{r}
dataset <- eventReactive(input$file1,{
     file <- input$file1
     ext <- tools::file_ext(file$datapath)
     req(file)
     validate(need(ext == "xlsx", "Please upload a xlsx file"))
     data_ <-  read_xlsx(file$datapath)
    })

DT::renderDataTable({
  dataset()
})
```

```{r}

print('dddd')
#renderTable({
 # if(is.null(input$file1)){return()}
 #else{
 #    file <- input$file1
 #    ext <- tools::file_ext(file$datapath)
 #     req(file)
 #    validate(need(ext == "xlsx", "Please upload a xlsx file"))
 #    data_ <-  read_xlsx(file$datapath)

# }

 #  })


```

```{r}

#renderRHandsontable({
#  rhandsontable(data_, width = 600, height = 300)# %>%
 # hot_col("factor_allow", allowInvalid = TRUE)
#})
```


### Saída

```{r}
#eventReactive({



#DRG <- NULL

#for(i in 1:length(data_$idade)){
 # if(data_$idade[i]<20 & data_$sexo[i]==1) {
 #   DRG[i] <- "DRG1"
 # }
 # else if(data_$idade[i]<20 & data_$sexo[i]==0) {
 #   DRG[i] <- "DRG2"
 # }
 # else if(data_$idade[i]>20 & data_$sexo[i]==1) {
 #   DRG[i] <- "DRG3"
 # }
 # if(data_$idade[i]>20 & data_$sexo[i]==0) {
 #   DRG[i] <- "DRG4"
 #   }
#}

#data_$DRG <- DRG

renderDT({
  input$run_button
      data(iris)
datatable(iris, extensions = "Buttons", options = list(dom = 'Blfrtip',
    buttons = c('copy', 'csv', 'excel' , 'pdf', 'print'), lengthMenu = list(c(15,25,50,-1),c(15, 25, 50, "All")),rownames = FALSE), filter = 'top')%>%
  formatStyle(
    'Species',backgroundColor = styleEqual(
      unique(iris$Species), c('lightblue', 'lightgreen', 'lightpink')), fontWeight = 'bold'
  )
#
#%>%
 # formatStyle('Species',  color = 'red', backgroundColor = 'yellow', fontWeight = 'bold')
})
```

